# Generated by Django 4.2.1 on 2023-05-30 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAdhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adhar_no', models.IntegerField(blank=True, null=True)),
                ('adhar_name', models.CharField(blank=True, max_length=15, null=True)),
                ('adhar_adress', models.CharField(blank=True, max_length=15, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(blank=True, max_length=15, null=True)),
                ('city_name', models.CharField(blank=True, max_length=15, null=True)),
                ('state_name', models.CharField(blank=True, max_length=15, null=True)),
                ('country_name', models.CharField(blank=True, max_length=15, null=True)),
                ('pincode', models.IntegerField(blank=True, max_length=15, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customers')),
            ],
        ),
    ]
